export const AUTH = {
  LOGIN: {
    TITLE:                "Sign in",
    SUBTITLE:             "Welcome back. Enter your credentials to continue.",
    EMAIL_LABEL:          "Email",
    EMAIL_PLACEHOLDER:    "you@example.com",
    PASSWORD_LABEL:       "Password",
    PASSWORD_PLACEHOLDER: "••••••••",
    SUBMIT:               "Sign in",
    LOADING:              "Signing in…",
    GOOGLE:               "Continue with Google",
    NO_ACCOUNT:           "No account?",
    CREATE_ONE:           "Create one",
    CHECK_EMAIL:          "Check your inbox to confirm your account, then sign in.",
  },
  REGISTER: {
    TITLE:                "Create account",
    SUBTITLE:             "Start tracking your trades and building your edge.",
    EMAIL_LABEL:          "Email",
    EMAIL_PLACEHOLDER:    "you@example.com",
    PASSWORD_LABEL:       "Password",
    PASSWORD_PLACEHOLDER: "••••••••",
    SUBMIT:               "Create account",
    LOADING:              "Creating account…",
    GOOGLE:               "Continue with Google",
    HAS_ACCOUNT:          "Already have an account?",
    SIGN_IN:              "Sign in",
  },
} as const;
