export const AUTH = {
  LOGIN: {
    TITLE:                "Sign in",
    SUBTITLE:             "Welcome back. Enter your credentials to continue.",
    EMAIL_LABEL:          "Email",
    EMAIL_PLACEHOLDER:    "you@example.com",
    PASSWORD_LABEL:       "Password",
    PASSWORD_PLACEHOLDER: "••••••••",
    SUBMIT:               "Sign in",
    LOADING:              "Signing in…",
    GOOGLE:               "Continue with Google",
    NO_ACCOUNT:           "No account?",
    CREATE_ONE:           "Create one",
    CHECK_EMAIL:          "Check your inbox to confirm your account, then sign in.",
    FORGOT:               "Forgot password?",
  },
  FORGOT: {
    TITLE:                "Reset password",
    SUBTITLE:             "Enter your email and we'll send you a reset link.",
    EMAIL_LABEL:          "Email",
    EMAIL_PLACEHOLDER:    "you@example.com",
    SUBMIT:               "Send reset link",
    LOADING:              "Sending…",
    BACK:                 "Back to sign in",
  },
  RESET: {
    TITLE:                "Set a new password",
    SUBTITLE:             "Choose a new password for your account.",
    PASSWORD_LABEL:       "New password",
    PASSWORD_PLACEHOLDER: "••••••••",
    SUBMIT:               "Update password",
    LOADING:              "Updating…",
  },
  REGISTER: {
    TITLE:                "Create account",
    SUBTITLE:             "Start tracking your trades and building your edge.",
    EMAIL_LABEL:          "Email",
    EMAIL_PLACEHOLDER:    "you@example.com",
    PASSWORD_LABEL:       "Password",
    PASSWORD_PLACEHOLDER: "••••••••",
    SUBMIT:               "Create account",
    LOADING:              "Creating account…",
    GOOGLE:               "Continue with Google",
    HAS_ACCOUNT:          "Already have an account?",
    SIGN_IN:              "Sign in",
  },
} as const;
