export const COMMON = {
  BRAND: {
    NAME:    "TradeOS",
    LOGO:    "T",
    TAGLINE: "Trading Journal",
    VERSION: "v0.1 · dev",
  },
  COMING_SOON:  "Coming soon",
  OR:           "or",
  ALL_ACCOUNTS: "All accounts",
  OPEN_MENU:    "Open menu",
  INSTALL_APP:  "Install app",
  NAV_LABELS: {
    DASHBOARD:  "Dashboard",
    TRADES:     "Trades",
    IMPORT:     "Import",
    REPORTS:    "Reports",
    PLAYBOOKS: "Playbooks",
    JOURNAL:    "Journal",
    ACCOUNTS:   "Accounts",
    GOALS:      "Goals",
    INSIGHTS:   "AI Insights",
  },
  SESSION: {
    LABEL:    "Session · —",
    NET_PNL:  "Net P&L",
    TRADES:   "Trades",
    WIN_RATE: "Win rate",
  },
  USER_FOOTER: {
    ACCOUNT:    "Account",
    INSTRUMENT: "NQ · live",
    LOG_OUT:    "Log out",
    SETTINGS:   "Settings",
  },
} as const;
