export const TRADES = {
  LIST: {
    TITLE:     "Trades",
    SUBTITLE:  "All trades · filterable · paginated",
    EMPTY:     "No trades match your filters",
    ERROR:     "Failed to load trades. Please try again.",
    NEW_TRADE: "New trade",
    HEADERS: {
      NUMBER:    "#",
      DATE:      "Date / Time",
      INSTRUMENT:"Instrument",
      DIRECTION: "Direction",
      QTY:       "Qty",
      ENTRY:     "Entry",
      EXIT:      "Exit",
      PNL_GROSS: "P&L Gross",
      COMM:      "Comm",
      NET_PNL:   "Net P&L",
      STRATEGY:  "Strategy",
      HOLD:      "Hold",
    },
    FILTERS: {
      INSTRUMENT: "Instrument",
      DIRECTION:  "Direction",
      STRATEGY:   "Strategy",
      ALL:        "All",
      LONG:       "Long",
      SHORT:      "Short",
    },
    RANGE: {
      DAY:   "Day",
      WEEK:  "Week",
      MONTH: "Month",
      YEAR:  "Year",
      ALL:   "All",
    },
    DIR_BADGE: {
      LONG:  "LONG",
      SHORT: "SHORT",
    },
    PAGINATION: {
      PREV:          "Prev",
      NEXT:          "Next",
      NO_TRADES:     "No trades",
      SHOWING:       "Showing",
      OF:            "of",
      TRADES_LABEL:  "trades",
    },
  },
  VIEW: {
    SUBTITLE: "Execution detail · MAE/MFE · notes",
  },
} as const;
