export const TRADES = {
  LIST: {
    TITLE:     "Trades",
    SUBTITLE:  "All trades · filterable · paginated",
    EMPTY:     "No trades match your filters",
    ERROR:     "Failed to load trades. Please try again.",
    NEW_TRADE: "New trade",
    HEADERS: {
      NUMBER:    "#",
      DATE:      "Date / Time",
      INSTRUMENT:"Instrument",
      DIRECTION: "Direction",
      QTY:       "Qty",
      ENTRY:     "Entry",
      EXIT:      "Exit",
      PNL_GROSS: "P&L Gross",
      COMM:      "Comm",
      NET_PNL:   "Net P&L",
      PLAYBOOK:  "Playbook",
      HOLD:      "Hold",
    },
    FILTERS: {
      INSTRUMENT: "Instrument",
      DIRECTION:  "Direction",
      PLAYBOOK:   "Playbook",
      OUTCOME:    "Outcome",
      MISTAKES:   "Mistakes",
      TAG:        "Tag",
      PNL:        "P&L",
      ALL:        "All",
      LONG:       "Long",
      SHORT:      "Short",
      WIN:        "Winners",
      LOSS:       "Losers",
      BE:         "Break-even",
      CLEAN:      "Clean (no mistakes)",
      ANY_MISTAKE:"Any mistake",
      PNL_MIN:    "Min $",
      PNL_MAX:    "Max $",
      APPLY:      "Apply",
      CLEAR:      "Clear",
      CLEAR_ALL:  "Clear filters",
    },
    RANGE: {
      DAY:   "Day",
      WEEK:  "Week",
      MONTH: "Month",
      YEAR:  "Year",
      ALL:   "All",
    },
    DIR_BADGE: {
      LONG:  "LONG",
      SHORT: "SHORT",
    },
    PAGINATION: {
      PREV:          "Prev",
      NEXT:          "Next",
      NO_TRADES:     "No trades",
      SHOWING:       "Showing",
      OF:            "of",
      TRADES_LABEL:  "trades",
    },
  },
  VIEW: {
    SUBTITLE: "Execution detail · MAE/MFE · notes",
  },
  FORM: {
    CREATE_TITLE:   "New trade",
    EDIT_TITLE:     "Edit trade",
    EDIT_CTA:       "Edit",
    ACCOUNT:        "Account",
    SELECT_ACCOUNT: "Select account…",
    INSTRUMENT:     "Instrument",
    DIRECTION:      "Direction",
    LONG:           "Long",
    SHORT:          "Short",
    CONTRACTS:      "Contracts",
    ENTRY_PRICE:    "Entry price",
    EXIT_PRICE:     "Exit price",
    ENTRY_TIME:     "Entry time",
    EXIT_TIME:      "Exit time",
    GROSS_PNL:      "Gross P&L",
    COMMISSION:     "Commission",
    NET_PNL:        "Net P&L",
    SESSION:        "Session",
    PLAYBOOK:       "Playbook",
    NOTES:          "Notes",
    NONE:           "— None —",
    AUTO:           "auto",
    SAVE:           "Save trade",
    CANCEL:         "Cancel",
    SUCCESS_CREATE: "Trade created",
    SUCCESS_EDIT:   "Trade updated",
    ERR_ACCOUNT:    "Select an account",
    ERR_INSTRUMENT: "Instrument is required",
    ERR_NUMBERS:    "Enter contracts and entry/exit prices",
    ERR_TIMES:      "Enter entry and exit times",
    ERR_ORDER:      "Exit must be after entry",
  },
} as const;
