export const TRADES = {
  LIST: {
    TITLE:     "Trades",
    SUBTITLE:  "All trades · filterable · paginated",
    EMPTY:     "No trades match your filters",
    ERROR:     "Failed to load trades. Please try again.",
    NEW_TRADE: "New trade",
    EXPORT:    "Export",
    EXPORTING: "Exporting…",
    EXPORT_ERROR: "Export failed. Please try again.",
    HEADERS: {
      NUMBER:    "#",
      DATE:      "Date / Time",
      INSTRUMENT:"Instrument",
      DIRECTION: "Direction",
      QTY:       "Qty",
      ENTRY:     "Entry",
      EXIT:      "Exit",
      PNL_GROSS: "P&L Gross",
      COMM:      "Comm",
      NET_PNL:   "Net P&L",
      PLAYBOOK:  "Playbook",
      HOLD:      "Hold",
    },
    FILTERS: {
      INSTRUMENT: "Instrument",
      DIRECTION:  "Direction",
      PLAYBOOK:   "Playbook",
      OUTCOME:    "Outcome",
      MISTAKES:   "Mistakes",
      TAG:        "Tag",
      PNL:        "P&L",
      ALL:        "All",
      LONG:       "Long",
      SHORT:      "Short",
      WIN:        "Winners",
      LOSS:       "Losers",
      BE:         "Break-even",
      CLEAN:      "Clean (no mistakes)",
      ANY_MISTAKE:"Any mistake",
      PNL_MIN:    "Min $",
      PNL_MAX:    "Max $",
      APPLY:      "Apply",
      CLEAR:      "Clear",
      CLEAR_ALL:  "Clear filters",
      BUTTON:     "Filters",
      SHEET_TITLE:"Filters",
    },
    RANGE: {
      DAY:   "Day",
      WEEK:  "Week",
      MONTH: "Month",
      YEAR:  "Year",
      ALL:   "All",
    },
    DIR_BADGE: {
      LONG:  "LONG",
      SHORT: "SHORT",
    },
    PAGINATION: {
      PREV:          "Prev",
      NEXT:          "Next",
      NO_TRADES:     "No trades",
      SHOWING:       "Showing",
      OF:            "of",
      TRADES_LABEL:  "trades",
    },
  },
  VIEW: {
    SUBTITLE:         "Execution detail · MAE/MFE · notes",
    TRADE_NUM_PREFIX: "Trade #",
    SETUP_MET:        "SETUP MET",
    SETUP_BROKEN:     "SETUP BROKEN",
    HELD:             "held",
  },
  HERO: {
    LONG:        "LONG",
    SHORT:       "SHORT",
    CONTRACT:    "contract",
    CONTRACTS:   "contracts",
    NET_PNL:     "NET P&L",
    ENTRY_PRICE: "ENTRY PRICE",
    EXIT_PRICE:  "EXIT PRICE",
    MOVE:        "MOVE",
    RISK_REWARD: "RISK:REWARD",
    GROSS_PNL:   "GROSS P&L",
    COMMISSION:  "COMMISSION",
    MAE:         "MAE",
    MFE:         "MFE",
    HOLD_TIME:   "HOLD TIME",
    PLAYBOOK:    "PLAYBOOK",
    SESSION:     "SESSION",
    ACCOUNT:     "ACCOUNT",
    PTS:         "pts",
    NONE:        "—",
  },
  EXCURSION: {
    TITLE:         "EXCURSION · MAE / MFE",
    MAE:           "MAE",
    MFE:           "MFE",
    NET:           "NET",
    EDGE:          "Edge:",
    CAPTURED:      "You captured",
    OF_BEST_MOVE:  "of the best move",
    GAVE_BACK:     "and gave back",
    IN_HEAT:       "in heat before exit",
    LOSS:          "Loss:",
    PRICE_MOVED:   "Price moved",
    IN_FAVOR:      "in your favor before reversing —",
    MAX_HEAT:      "max heat",
    OF_MFE:        "of MFE",
    PRICE_AGAINST: "Price moved straight against you — max heat",
  },
  EXECUTIONS: {
    TITLE:       "Executions",
    ENTRY:       "ENTRY",
    EXIT:        "EXIT",
    STOP:        "STOP",
    LONG:        "LONG",
    SHORT:       "SHORT",
    EST:         "est.",
    SET_STOP:    "— set stop",
    HOLD_TIME:   "Hold time",
    PTS:         "pts",
    TITLE_EST:   "Estimated from MAE · click to set the real stop",
    TITLE_EDIT:  "Click to edit",
  },
  ATTACHMENTS: {
    TITLE:      "Attachments",
    LOADING:    "Loading…",
    UPLOADING:  "Uploading…",
    DROP:       "Drop screenshots or charts",
    FORMATS:    "PNG · JPG · WebP",
    ADD_MORE:   "+ Add more",
    ZOOM_IN:    "Zoom in (+)",
    ZOOM_OUT:   "Zoom out (-)",
    RESET_ZOOM: "Reset zoom (0)",
    DELETE:     "Delete",
    CLOSE:      "Close (Esc)",
  },
  DELETE: {
    CONFIRM_Q: "Delete trade?",
    DELETING:  "Deleting…",
    CONFIRM:   "Confirm",
    CANCEL:    "Cancel",
    DELETE:    "Delete",
    TITLE:     "Delete this trade",
  },
  CHART: {
    TIMEFRAME:        "1 min",
    OPEN:             "O",
    PTS:              "pts",
    SOURCE_REAL:      "Real",
    SOURCE_SYNTHETIC: "Simulated",
    RETRY:            "Retry",
    LOADING:          "Loading data…",
    TYPE_CANDLES:     "Candles",
    TYPE_LINE:        "Line",
    TYPE_BARS:        "Bars",
    LEGEND_ENTRY:     "Entry",
    LEGEND_EXIT:      "Exit",
    LEGEND_STOP:      "Stop",
    LEGEND_TARGET:    "Target",
  },
  SIDEBAR: {
    PLAYBOOK:          "Playbook",
    NONE:              "— None —",
    SETUP_CHECKLIST:   "Setup checklist",
    VALID:             "VALID",
    INCOMPLETE:        "INCOMPLETE",
    GROUP_ENTRY:       "Entry",
    GROUP_EXIT:        "Exit",
    GROUP_CONDITIONS:  "Conditions",
    MIN:               "min",
    NOTES:             "Notes",
    NOTES_PLACEHOLDER: "What happened? What did you learn?",
    AUTOSAVED:         "autosaved",
    SAVE:              "Save",
    SAVE_SHORTCUT:     "⌘S",
    TAGS:              "Tags",
    ADD_TAG:           "+ add",
    MISTAKES:          "Mistakes",
    MISTAKES_HINT:     "Tag what went wrong (optional).",
  },
  FORM: {
    CREATE_TITLE:   "New trade",
    EDIT_TITLE:     "Edit trade",
    EDIT_CTA:       "Edit",
    ACCOUNT:        "Account",
    SELECT_ACCOUNT: "Select account…",
    INSTRUMENT:     "Instrument",
    DIRECTION:      "Direction",
    LONG:           "Long",
    SHORT:          "Short",
    CONTRACTS:      "Contracts",
    ENTRY_PRICE:    "Entry price",
    EXIT_PRICE:     "Exit price",
    ENTRY_TIME:     "Entry time",
    EXIT_TIME:      "Exit time",
    GROSS_PNL:      "Gross P&L",
    COMMISSION:     "Commission",
    NET_PNL:        "Net P&L",
    SESSION:        "Session",
    STOP_PRICE:     "Stop loss",
    STOP_HINT:      "optional",
    PLAYBOOK:       "Playbook",
    NOTES:          "Notes",
    NOTES_PLACEHOLDER: "Optional…",
    NONE:           "— None —",
    TAB_DETAILS:    "Details",
    TAB_ATTACHMENTS: "Attachments",
    ATTACH_ADD:     "Add images",
    ATTACH_HINT:    "Drop screenshots or charts · uploaded when you save",
    AUTO:           "auto",
    SAVE:           "Save trade",
    CANCEL:         "Cancel",
    SUCCESS_CREATE: "Trade created",
    SUCCESS_EDIT:   "Trade updated",
    ERR_ACCOUNT:    "Select an account",
    ERR_INSTRUMENT: "Instrument is required",
    ERR_NUMBERS:    "Enter contracts and entry/exit prices",
    ERR_TIMES:      "Enter entry and exit times",
    ERR_ORDER:      "Exit must be after entry",
  },
} as const;
