export const IMPORT = {
  TITLE:    "Import",
  SUBTITLE: "Import trades from any broker · CSV",
  DROP: {
    HEADLINE: "Drop your CSV here",
    SUBTITLE: "or click to browse — works with any broker",
    HINT:     "Auto-detects NinjaTrader · map columns for any other broker",
    BROKERS:  ["NinjaTrader", "Tradovate", "TradeStation", "Interactive Brokers"],
    ANY:      "Any CSV",
  },
  PREVIEW: {
    PARSED_BADGE:    "Parsed",
    FILE_META:       "Parsed {rows} rows · mapped as {format}",
    METRIC_DETECTED: "Detected",
    METRIC_NEW:      "New",
    METRIC_DUPLICATES: "Duplicates",
    METRIC_EXCLUDED: "Excluded",
    METRIC_ERRORS:   "Errors",
    TABLE_HEADERS: {
      KEEP:       "Keep",
      STATUS:     "Status",
      TIME:       "Time",
      INSTRUMENT: "Instrument",
      DIR:        "Dir",
      QTY:        "Qty",
      ENTRY:      "Entry",
      EXIT:       "Exit",
      NET_PNL:    "Net P&L",
    },
    STATUS_NEW:     "NEW",
    STATUS_DUP:     "DUP",
    STATUS_SKIPPED: "SKIPPED",
    KEEP_TITLE:     "Uncheck to exclude this trade from your metrics",
    DIR_LONG:       "LONG",
    DIR_SHORT:      "SHORT",
    FOOTER_SUMMARY: "{new} new · {dup} duplicates · {excluded} excluded · commissions auto-calculated",
    DELETE_WARNING: "{count} already-imported trades will be deleted",
    CANCEL:         "Cancel",
    IMPORT_CTA:     "Import {count} trades →",
    EXCLUDE_CTA:    "Apply exclusions →",
    IMPORT_ANOTHER: "Import another file",
    MAPPING_LABEL:  "Mapping:",
    MAPPING_VALUE:  "NinjaTrader v8",
  },
  FILTER: {
    TITLE:       "Exclude break-even trades",
    HINT:        "Trades you exclude are remembered — re-importing the same CSV will not bring them back.",
    THRESHOLD:   "|Net P&L| ≤",
    APPLY:       "Exclude {count} trades",
    APPLY_EMPTY: "Exclude",
    KEEP_ALL:    "Keep all",
    EXCLUDED:    "{count} excluded",
  },
  MAPPING: {
    TITLE:           "Map your columns",
    SUBTITLE:        "We couldn't auto-detect this broker. Match each field to a column from your CSV.",
    REQUIRED:        "required",
    NONE:            "—",
    ACCOUNT_DEFAULT: "Default account",
    ACCOUNT_HINT:    "Used for rows with no account column.",
    ACCOUNT_PLACEHOLDER: "e.g. Topstep 50K",
    SAMPLE:          "Sample from your file",
    CONTINUE:        "Continue",
    CANCEL:          "Cancel",
    ERR_REQUIRED:    "Map all required fields first.",
    ERR_ACCOUNT:     "Map an account column or set a default account.",
    ERR_NO_ROWS:     "No valid rows after mapping. Check the columns and try again.",
  },
  ERRORS: {
    TITLE:      "Errors · {count} rows skipped",
    LINE:       "Line",
    ACCOUNT:    "Account",
    INSTRUMENT: "Instrument",
    REASON:     "Reason",
    NONE:       "—",
  },
  STATUS: {
    IMPORTING: "Importing…",
    DONE:      "✓ Imported {count} trades",
    APPLYING:  "Applying…",
  },
  TOAST: {
    PARSE_ERROR:    "Could not parse the file. Check it's a NinjaTrader export.",
    IMPORT_SUCCESS: "{count} trades imported successfully.",
    IMPORT_ERROR:   "Import failed. Please try again.",
    NO_NEW_ROWS:    "All trades in this file already exist.",
    NOTHING_TO_DO:  "Nothing to import — every row is a duplicate or already excluded.",
    EXCLUDED_ONLY:  "{count} trades excluded. They will not come back on re-import.",
    IMPORT_MIXED:   "{count} trades imported · {excluded} excluded.",
  },
} as const;
