export const IMPORT = {
  TITLE:    "Import",
  SUBTITLE: "NinjaTrader · TradeStation · CSV",
  DROP: {
    HEADLINE:          "Drop your CSV here",
    SUBTITLE:          "or click to browse · NinjaTrader export",
    BADGE_NINJATRADER: "NinjaTrader.csv",
    BADGE_TRADESTATION: "TradeStation.csv",
  },
  PREVIEW: {
    PARSED_BADGE:    "Parsed",
    FILE_META:       "Parsed {rows} rows · mapped as {format}",
    METRIC_DETECTED: "Detected",
    METRIC_NEW:      "New",
    METRIC_DUPLICATES: "Duplicates",
    METRIC_ERRORS:   "Errors",
    TABLE_HEADERS: {
      STATUS:     "Status",
      TIME:       "Time",
      INSTRUMENT: "Instrument",
      DIR:        "Dir",
      QTY:        "Qty",
      ENTRY:      "Entry",
      EXIT:       "Exit",
      NET_PNL:    "Net P&L",
    },
    STATUS_NEW:     "NEW",
    STATUS_DUP:     "DUP",
    DIR_LONG:       "LONG",
    DIR_SHORT:      "SHORT",
    FOOTER_SUMMARY: "{new} new · {dup} duplicates · commissions auto-calculated",
    CANCEL:         "Cancel",
    IMPORT_CTA:     "Import {count} trades →",
    IMPORT_ANOTHER: "Import another file",
    MAPPING_LABEL:  "Mapping:",
    MAPPING_VALUE:  "NinjaTrader v8",
  },
  STATUS: {
    IMPORTING: "Importing…",
    DONE:      "✓ Imported {count} trades",
  },
  TOAST: {
    PARSE_ERROR:    "Could not parse the file. Check it's a NinjaTrader export.",
    IMPORT_SUCCESS: "{count} trades imported successfully.",
    IMPORT_ERROR:   "Import failed. Please try again.",
    NO_NEW_ROWS:    "All trades in this file already exist.",
  },
} as const;
