export const PLAYBOOKS = {
  TITLE:            "Playbooks",
  SUBTITLE:         "Define setups · tag trades · track edge",
  SUBTITLE_FALLBACK: "Track which setups are working",

  CARD: {
    TRADES_LABEL:   "Trades",
    WIN_RATE_LABEL: "Win rate",
    NET_PNL_LABEL:  "Net P&L",
    EXPECTANCY_R:   "Expectancy (R)",
    PROFIT_FACTOR:  "Profit factor",
    AVG_WL:         "Avg W/L",
    NO_DESCRIPTION: "No description",
    STATUS_ACTIVE:  "ACTIVE",
    STATUS_ARCHIVED: "ARCHIVED",
    CREATED_PREFIX: "Created",
  },

  DETAIL: {
    BACK:           "← Playbooks",
    EDIT:           "Edit",
    RULES:          "Rules",
    NO_RULES:       "No rules defined yet.",
    EQUITY:         "Equity curve",
    R_DIST:         "R-multiple distribution",
    NO_R:           "Set stops or a risk per trade on the account to see R-multiples.",
    BY_INSTRUMENT:  "By instrument",
    EMPTY:          "No trades tagged to this playbook yet.",
    ADHERENCE:      "Setup adherence",
    FOLLOWED:       "Followed setup",
    BROKE:          "Broke rules",
    TRACKED:        "tracked",
    ADH_NONE:       "Tick the rules you followed on each trade (in the trade view) to see how adherence affects results.",
    ADH_STATS: {
      TRADES:       "Trades",
      WIN_RATE:     "Win %",
      NET_PNL:      "Net P&L",
      EXPECTANCY_R: "Expectancy (R)",
    },
    STATS: {
      NET_PNL:      "Net P&L",
      WIN_RATE:     "Win %",
      PROFIT_FACTOR:"Profit factor",
      EXPECTANCY_R: "Expectancy (R)",
      AVG_WL:       "Avg W/L",
      TRADES:       "Trades",
      SQN:          "SQN",
      MAX_DD:       "Max drawdown",
    },
    TABLE: {
      INSTRUMENT: "Instrument",
      TRADES:     "Trades",
      WIN_RATE:   "Win %",
      NET_PNL:    "Net P&L",
    },
  },

  EDITOR: {
    CREATE_TITLE:           "New playbook",
    EDIT_TITLE:             "Edit playbook",
    CAPTION:                "Define a setup so you can tag trades and report on its edge.",
    NAME_LABEL:             "Name",
    NAME_PLACEHOLDER:       "e.g. London Open Fade",
    DESCRIPTION_LABEL:      "Description",
    DESCRIPTION_PLACEHOLDER: "Brief description of the setup",
    ENTRY_CRITERIA:         "Entry criteria",
    EXIT_CRITERIA:          "Exit criteria",
    MARKET_CONDITIONS:      "Market conditions",
    ADD_RULE:               "+ Add rule",
    RULE_PLACEHOLDER:       "Add a rule…",
    SAVE:                   "Save changes",
    CREATE:                 "Create playbook",
    CANCEL:                 "Cancel",
    ARCHIVE:                "Archive playbook",
    ARCHIVE_CONFIRM:        "Click again to archive",
    RESTORE:                "Restore playbook",
  },

  NEW_CARD: {
    TITLE: "New playbook",
    BODY:  "Define rules and tag trades",
  },

  EMPTY: {
    HEADLINE: "No playbooks yet",
    BODY:     "Create a playbook to tag your trades and track which setups are working.",
    CTA:      "New playbook",
  },

  TOAST: {
    CREATE_SUCCESS: "Playbook created.",
    SAVE_SUCCESS:   "Playbook updated.",
    ARCHIVED:       "Playbook archived.",
    RESTORED:       "Playbook restored.",
    ERROR:          "Could not save. Please try again.",
  },

  ERROR: {
    LOAD_FAILED: "Could not load playbooks.",
    TITLE:       "Something went wrong",
    MESSAGE:     "Failed to load playbooks.",
    RETRY:       "Try again",
  },
} as const
